import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  useEffect(() => {

  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Template Example app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          
          result
        </h1>

        
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      
    }
  }
}