import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import agent from "../utils/agent";

export default function Home({ data }) {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Template Example app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Server Side fetch</h1>
        <p className={styles.description}>
          <strong>Result:</strong>{" "}
          {data?.message}
        </p>

        <Link href="/" passHref>
          <a>Back to Main page</a>
        </Link>
        <button
          onClick={() =>
            agent()
              .logout()
              .then(() => router.push("/login"))
          }
        >
          Logout
        </button>
      </main>
    </div>
  );
}

/**
 * 
 * @param {import("next").GetServerSidePropsContext} context 
 * @returns 
 */
export async function getServerSideProps(context) {
  try {
    const res = await agent(context).example();
    return {
      props: { data: res.data },
    };
  } catch(err) {
    // console.log(err);
    console.log(err?.response?.data);
    return {
      redirect: {
        permanent: false,
        destination: context.resolvedUrl
          ? `/login?from=${context.resolvedUrl}`
          : "/login",
      }
    };
  }
}
